"""empty message

Revision ID: 1178cb4c5361
Revises: ed971656d4f7
Create Date: 2021-10-10 23:21:08.658546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1178cb4c5361'
down_revision = 'ed971656d4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vinnumber', sa.String(length=25), nullable=True))
    op.add_column('vehicles', sa.Column('licenseplate', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'licenseplate')
    op.drop_column('vehicles', 'vinnumber')
    # ### end Alembic commands ###
