"""empty message

Revision ID: 126cc00fb294
Revises: 6e44cfc4bba5
Create Date: 2021-10-09 23:19:58.191004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126cc00fb294'
down_revision = '6e44cfc4bba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('pictureURL', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'pictureURL')
    # ### end Alembic commands ###
