"""empty message

Revision ID: 14d7d5cc5de1
Revises: d39c4f5f6399
Create Date: 2021-10-16 23:02:12.266965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d7d5cc5de1'
down_revision = 'd39c4f5f6399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_filename', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('avatar_mimetype', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'user', ['avatar'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'avatar_mimetype')
    op.drop_column('user', 'avatar_filename')
    # ### end Alembic commands ###
