"""empty message

Revision ID: 269353c552b4
Revises: 1178cb4c5361
Create Date: 2021-10-11 00:43:07.076596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269353c552b4'
down_revision = '1178cb4c5361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('curown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'curown')
    # ### end Alembic commands ###
