"""empty message

Revision ID: 5663ef59922a
Revises: 6c824dded1ae
Create Date: 2021-10-14 22:26:17.848403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5663ef59922a'
down_revision = '6c824dded1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surgeries', 'enddate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surgeries', sa.Column('enddate', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
