"""empty message

Revision ID: 5def3aa77bfd
Revises: fbde38b5cce9
Create Date: 2021-10-18 21:08:29.011131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5def3aa77bfd'
down_revision = 'fbde38b5cce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('howoften', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['avatar'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cpap', schema=None) as batch_op:
        batch_op.drop_column('howoften')

    # ### end Alembic commands ###
