"""empty message

Revision ID: 6647cc5c1b41
Revises: b1a4023cec83
Create Date: 2021-10-12 02:24:13.163165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6647cc5c1b41'
down_revision = 'b1a4023cec83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('user', sa.Column('zip', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'zip')
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
