"""empty message

Revision ID: 6c824dded1ae
Revises: fd415bccfc38
Create Date: 2021-10-13 23:40:28.212202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c824dded1ae'
down_revision = 'fd415bccfc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('userid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'userid')
    # ### end Alembic commands ###
