"""empty message

Revision ID: 6e44cfc4bba5
Revises: 
Create Date: 2021-10-09 23:17:37.348284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e44cfc4bba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=75), nullable=True),
    sa.Column('model', sa.String(length=75), nullable=True),
    sa.Column('color', sa.String(length=25), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('sell_date', sa.DateTime(), nullable=True),
    sa.Column('reasonforsale', sa.String(length=75), nullable=True),
    sa.Column('saleamount', sa.Float(), nullable=True),
    sa.Column('licenseplate', sa.String(length=20), nullable=True),
    sa.Column('purchaseprice', sa.Float(), nullable=True),
    sa.Column('purchasefrom', sa.String(length=75), nullable=True),
    sa.Column('vinnumber', sa.String(length=25), nullable=True),
    sa.Column('tagsexpire', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licenseplate'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('vinnumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
