"""empty message

Revision ID: 869e28877680
Revises: 2781214068d3
Create Date: 2021-10-18 20:50:56.362274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869e28877680'
down_revision = '2781214068d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CPAP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('lastordered', sa.Date(), nullable=True),
    sa.Column('nextorderdate', sa.Date(), nullable=True),
    sa.Column('imageURL', sa.Text(), nullable=True),
    sa.Column('itemnum', sa.Text(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['avatar'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('CPAP')
    # ### end Alembic commands ###
