"""empty message

Revision ID: ef93feb01873
Revises: 14d7d5cc5de1
Create Date: 2021-10-18 00:02:03.326730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef93feb01873'
down_revision = '14d7d5cc5de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catagory', sa.Text(), nullable=True),
    sa.Column('subcatagory', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('link1', sa.Text(), nullable=True),
    sa.Column('link2', sa.Text(), nullable=True),
    sa.Column('link3', sa.Text(), nullable=True),
    sa.Column('link4', sa.Text(), nullable=True),
    sa.Column('link5', sa.Text(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['avatar'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('code_snips')
    # ### end Alembic commands ###
