"""empty message

Revision ID: fd415bccfc38
Revises: 9c5313c9bbc3
Create Date: 2021-10-13 23:22:24.101487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd415bccfc38'
down_revision = '9c5313c9bbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_planner', sa.Boolean(), nullable=True),
    sa.Column('menu_rec', sa.Boolean(), nullable=True),
    sa.Column('menu_shopping', sa.Boolean(), nullable=True),
    sa.Column('menu_extra1', sa.Boolean(), nullable=True),
    sa.Column('menu_extra2', sa.Boolean(), nullable=True),
    sa.Column('menu_extra3', sa.Boolean(), nullable=True),
    sa.Column('menu_extra4', sa.Boolean(), nullable=True),
    sa.Column('menu_extra5', sa.Boolean(), nullable=True),
    sa.Column('menu_extra1_label', sa.String(length=30), nullable=True),
    sa.Column('menu_extra1_url', sa.String(length=200), nullable=True),
    sa.Column('menu_extra2_label', sa.String(length=30), nullable=True),
    sa.Column('menu_extra2_url', sa.String(length=200), nullable=True),
    sa.Column('menu_extra3_label', sa.String(length=30), nullable=True),
    sa.Column('menu_extra3_url', sa.String(length=200), nullable=True),
    sa.Column('menu_extra4_label', sa.String(length=30), nullable=True),
    sa.Column('menu_extra4_url', sa.String(length=200), nullable=True),
    sa.Column('menu_extra5_label', sa.String(length=30), nullable=True),
    sa.Column('menu_extra5_url', sa.String(length=200), nullable=True),
    sa.Column('health_facilities', sa.Boolean(), nullable=True),
    sa.Column('health_doctors', sa.Boolean(), nullable=True),
    sa.Column('health_meds', sa.Boolean(), nullable=True),
    sa.Column('health_medlist', sa.Boolean(), nullable=True),
    sa.Column('health_hospt', sa.Boolean(), nullable=True),
    sa.Column('health_surg', sa.Boolean(), nullable=True),
    sa.Column('health_allergies', sa.Boolean(), nullable=True),
    sa.Column('health_a1c', sa.Boolean(), nullable=True),
    sa.Column('health_cpap', sa.Boolean(), nullable=True),
    sa.Column('health_extra1', sa.Boolean(), nullable=True),
    sa.Column('health_extra2', sa.Boolean(), nullable=True),
    sa.Column('health_extra3', sa.Boolean(), nullable=True),
    sa.Column('health_extra4', sa.Boolean(), nullable=True),
    sa.Column('health_extra5', sa.Boolean(), nullable=True),
    sa.Column('health_extra1_label', sa.String(length=30), nullable=True),
    sa.Column('health_extra1_url', sa.String(length=200), nullable=True),
    sa.Column('health_extra2_label', sa.String(length=30), nullable=True),
    sa.Column('health_extra2_url', sa.String(length=200), nullable=True),
    sa.Column('health_extra3_label', sa.String(length=30), nullable=True),
    sa.Column('health_extra3_url', sa.String(length=200), nullable=True),
    sa.Column('health_extra4_label', sa.String(length=30), nullable=True),
    sa.Column('health_extra4_url', sa.String(length=200), nullable=True),
    sa.Column('health_extra5_label', sa.String(length=30), nullable=True),
    sa.Column('health_extra5_url', sa.String(length=200), nullable=True),
    sa.Column('prod_goals', sa.Boolean(), nullable=True),
    sa.Column('prod_projects', sa.Boolean(), nullable=True),
    sa.Column('prod_tasks', sa.Boolean(), nullable=True),
    sa.Column('prod_extra1', sa.Boolean(), nullable=True),
    sa.Column('prod_extra2', sa.Boolean(), nullable=True),
    sa.Column('prod_extra3', sa.Boolean(), nullable=True),
    sa.Column('prod_extra4', sa.Boolean(), nullable=True),
    sa.Column('prod_extra5', sa.Boolean(), nullable=True),
    sa.Column('prod_extra1_label', sa.String(length=30), nullable=True),
    sa.Column('prod_extra1_url', sa.String(length=200), nullable=True),
    sa.Column('prod_extra2_label', sa.String(length=30), nullable=True),
    sa.Column('prod_extra2_url', sa.String(length=200), nullable=True),
    sa.Column('prod_extra3_label', sa.String(length=30), nullable=True),
    sa.Column('prod_extra3_url', sa.String(length=200), nullable=True),
    sa.Column('prod_extra4_label', sa.String(length=30), nullable=True),
    sa.Column('prod_extra4_url', sa.String(length=200), nullable=True),
    sa.Column('prod_extra5_label', sa.String(length=30), nullable=True),
    sa.Column('prod_extra5_url', sa.String(length=200), nullable=True),
    sa.Column('personal_cars', sa.Boolean(), nullable=True),
    sa.Column('personal_wifi', sa.Boolean(), nullable=True),
    sa.Column('personal_extra1', sa.Boolean(), nullable=True),
    sa.Column('personal_extra2', sa.Boolean(), nullable=True),
    sa.Column('personal_extra3', sa.Boolean(), nullable=True),
    sa.Column('personal_extra4', sa.Boolean(), nullable=True),
    sa.Column('personal_extra5', sa.Boolean(), nullable=True),
    sa.Column('personal_extra1_label', sa.String(length=30), nullable=True),
    sa.Column('personal_extra1_url', sa.String(length=200), nullable=True),
    sa.Column('personal_extra2_label', sa.String(length=30), nullable=True),
    sa.Column('personal_extra2_url', sa.String(length=200), nullable=True),
    sa.Column('personal_extra3_label', sa.String(length=30), nullable=True),
    sa.Column('personal_extra3_url', sa.String(length=200), nullable=True),
    sa.Column('personal_extra4_label', sa.String(length=30), nullable=True),
    sa.Column('personal_extra4_url', sa.String(length=200), nullable=True),
    sa.Column('personal_extra5_label', sa.String(length=30), nullable=True),
    sa.Column('personal_extra5_url', sa.String(length=200), nullable=True),
    sa.Column('other_extra1', sa.Boolean(), nullable=True),
    sa.Column('other_extra2', sa.Boolean(), nullable=True),
    sa.Column('other_extra3', sa.Boolean(), nullable=True),
    sa.Column('other_extra4', sa.Boolean(), nullable=True),
    sa.Column('other_extra5', sa.Boolean(), nullable=True),
    sa.Column('other_extra1_label', sa.String(length=30), nullable=True),
    sa.Column('other_extra1_url', sa.String(length=200), nullable=True),
    sa.Column('other_extra2_label', sa.String(length=30), nullable=True),
    sa.Column('other_extra2_url', sa.String(length=200), nullable=True),
    sa.Column('other_extra3_label', sa.String(length=30), nullable=True),
    sa.Column('other_extra3_url', sa.String(length=200), nullable=True),
    sa.Column('other_extra4_label', sa.String(length=30), nullable=True),
    sa.Column('other_extra4_url', sa.String(length=200), nullable=True),
    sa.Column('other_extra5_label', sa.String(length=30), nullable=True),
    sa.Column('other_extra5_url', sa.String(length=200), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
